import Axios from "axios";
import { useState,useEffect } from "react";
import "./index.css";
const RandomImages=()=>{
    
    const [imgUrls,setUrls]=useState([]);

    useEffect(async ()=>{
       const response= await Axios.get("http://localhost:3004/obtain-Random-images");
       const data=response.data;
       var list=[];
       data.map((obj,idx)=>{
          list.push(obj.imgURL);
       })
       console.log(list);
       setUrls(list);
    },[])

    return (
        <>
        <div>
           <h> Images generated by our Ai model</h>
           <div>
               { imgUrls && imgUrls.map((url,idx)=>{
                  return (
                    <img  key={idx} className="RandomImg"
                     src={`http://localhost:3004/obtain-images/${url}`}/>
                  )
               })
               }
           </div>
        </div>
        
        </>
    );
}

export default RandomImages;