import Axios from "axios";
import { useState,useEffect } from "react";
import "./index.css";
const RandomImages=()=>{
    
    const [imgUrls,setUrls]=useState([]);

    useEffect(async ()=>{
       const response= await Axios.get("http://localhost:3004/obtain-Random-images");
       const data=response.data;
       var list=[];
       data.map((obj,idx)=>{
          list.push(obj.imgURL);
       })
       console.log(list);
       setUrls(list);
       //setTimeout(()=>{setShowimg(true)},2000)
    },[])

    return (
        <>
        <div className="Randomimgpage">
           <h1 className="RandomPageHeading"> Images generated by our AI model</h1>
           <div className="RandomimgContainer">
               { imgUrls && imgUrls.map((url,idx)=>{
                  return (
                    <img  key={idx} className="RandomImg"
                     src={`http://localhost:3004/obtain-images/${url}`} />
                  )
               })
               }
           </div>
        </div>
        
        </>
    );
}

export default RandomImages;